/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PaperFilter {
  'difficulty' : [] | [string],
  'part' : [] | [string],
  'unitId' : [] | [string],
  'subtopicId' : [] | [string],
  'questionCount' : bigint,
  'topicId' : [] | [string],
}
export interface PaperGenerationRequest {
  'selectedTopic' : [] | [string],
  'selectedDifficulty' : [] | [string],
  'totalQuestions' : bigint,
  'questions' : Array<Question>,
  'selectedSubtopic' : [] | [string],
  'selectedPart' : [] | [string],
  'selectedUnit' : [] | [string],
}
export interface Question {
  'id' : string,
  'difficulty' : string,
  'explanation' : [] | [string],
  'createdAt' : bigint,
  'part' : string,
  'text' : string,
  'correctAnswer' : string,
  'unitId' : string,
  'subtopicId' : string,
  'optionA' : string,
  'optionB' : string,
  'optionC' : string,
  'optionD' : string,
  'topicId' : string,
}
export interface QuestionCountStats {
  'difficulty' : string,
  'part' : string,
  'count' : bigint,
  'unitId' : string,
}
export interface Settings {
  'watermarkText' : string,
  'instituteName' : string,
  'negativeMarkingValue' : number,
  'negativeMarkingEnabled' : boolean,
  'footerText' : string,
}
export interface Subtopic { 'id' : string, 'name' : string }
export interface SyllabusUnit {
  'id' : string,
  'name' : string,
  'topics' : Array<Topic>,
}
export interface Topic {
  'id' : string,
  'name' : string,
  'subtopics' : Array<Subtopic>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSyllabusUnit' : ActorMethod<[SyllabusUnit], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createQuestion' : ActorMethod<[Question], string>,
  'deleteQuestion' : ActorMethod<[string], undefined>,
  'generatePaper' : ActorMethod<[PaperFilter], PaperGenerationRequest>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuestion' : ActorMethod<[string], Question>,
  'getQuestionStats' : ActorMethod<[], Array<QuestionCountStats>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getSyllabus' : ActorMethod<[], Array<SyllabusUnit>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchQuestions' : ActorMethod<[string], Array<Question>>,
  'updateQuestion' : ActorMethod<[Question], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];