/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Subtopic = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Topic = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'subtopics' : IDL.Vec(Subtopic),
});
export const SyllabusUnit = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'topics' : IDL.Vec(Topic),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'difficulty' : IDL.Text,
  'explanation' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'part' : IDL.Text,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'unitId' : IDL.Text,
  'subtopicId' : IDL.Text,
  'optionA' : IDL.Text,
  'optionB' : IDL.Text,
  'optionC' : IDL.Text,
  'optionD' : IDL.Text,
  'topicId' : IDL.Text,
});
export const PaperFilter = IDL.Record({
  'difficulty' : IDL.Opt(IDL.Text),
  'part' : IDL.Opt(IDL.Text),
  'unitId' : IDL.Opt(IDL.Text),
  'subtopicId' : IDL.Opt(IDL.Text),
  'questionCount' : IDL.Nat,
  'topicId' : IDL.Opt(IDL.Text),
});
export const PaperGenerationRequest = IDL.Record({
  'selectedTopic' : IDL.Opt(IDL.Text),
  'selectedDifficulty' : IDL.Opt(IDL.Text),
  'totalQuestions' : IDL.Nat,
  'questions' : IDL.Vec(Question),
  'selectedSubtopic' : IDL.Opt(IDL.Text),
  'selectedPart' : IDL.Opt(IDL.Text),
  'selectedUnit' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QuestionCountStats = IDL.Record({
  'difficulty' : IDL.Text,
  'part' : IDL.Text,
  'count' : IDL.Nat,
  'unitId' : IDL.Text,
});
export const Settings = IDL.Record({
  'watermarkText' : IDL.Text,
  'instituteName' : IDL.Text,
  'negativeMarkingValue' : IDL.Float64,
  'negativeMarkingEnabled' : IDL.Bool,
  'footerText' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSyllabusUnit' : IDL.Func([SyllabusUnit], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createQuestion' : IDL.Func([Question], [IDL.Text], []),
  'deleteQuestion' : IDL.Func([IDL.Text], [], []),
  'generatePaper' : IDL.Func(
      [PaperFilter],
      [PaperGenerationRequest],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuestion' : IDL.Func([IDL.Text], [Question], ['query']),
  'getQuestionStats' : IDL.Func([], [IDL.Vec(QuestionCountStats)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getSyllabus' : IDL.Func([], [IDL.Vec(SyllabusUnit)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'updateQuestion' : IDL.Func([Question], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Subtopic = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Topic = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'subtopics' : IDL.Vec(Subtopic),
  });
  const SyllabusUnit = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'topics' : IDL.Vec(Topic),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'difficulty' : IDL.Text,
    'explanation' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'part' : IDL.Text,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'unitId' : IDL.Text,
    'subtopicId' : IDL.Text,
    'optionA' : IDL.Text,
    'optionB' : IDL.Text,
    'optionC' : IDL.Text,
    'optionD' : IDL.Text,
    'topicId' : IDL.Text,
  });
  const PaperFilter = IDL.Record({
    'difficulty' : IDL.Opt(IDL.Text),
    'part' : IDL.Opt(IDL.Text),
    'unitId' : IDL.Opt(IDL.Text),
    'subtopicId' : IDL.Opt(IDL.Text),
    'questionCount' : IDL.Nat,
    'topicId' : IDL.Opt(IDL.Text),
  });
  const PaperGenerationRequest = IDL.Record({
    'selectedTopic' : IDL.Opt(IDL.Text),
    'selectedDifficulty' : IDL.Opt(IDL.Text),
    'totalQuestions' : IDL.Nat,
    'questions' : IDL.Vec(Question),
    'selectedSubtopic' : IDL.Opt(IDL.Text),
    'selectedPart' : IDL.Opt(IDL.Text),
    'selectedUnit' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QuestionCountStats = IDL.Record({
    'difficulty' : IDL.Text,
    'part' : IDL.Text,
    'count' : IDL.Nat,
    'unitId' : IDL.Text,
  });
  const Settings = IDL.Record({
    'watermarkText' : IDL.Text,
    'instituteName' : IDL.Text,
    'negativeMarkingValue' : IDL.Float64,
    'negativeMarkingEnabled' : IDL.Bool,
    'footerText' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSyllabusUnit' : IDL.Func([SyllabusUnit], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createQuestion' : IDL.Func([Question], [IDL.Text], []),
    'deleteQuestion' : IDL.Func([IDL.Text], [], []),
    'generatePaper' : IDL.Func(
        [PaperFilter],
        [PaperGenerationRequest],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuestion' : IDL.Func([IDL.Text], [Question], ['query']),
    'getQuestionStats' : IDL.Func([], [IDL.Vec(QuestionCountStats)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getSyllabus' : IDL.Func([], [IDL.Vec(SyllabusUnit)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'updateQuestion' : IDL.Func([Question], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };